### ISSUE TITLE
net.Socket is not a constructor 

### ISSUE THREAD

**Issue by nsssim** [durairajasivam/TCP-Raw-Socket-with-Vue-and-Electron#2]
I am not sure if you can use "net" library in the browser , This module is meant to be used only on Node.js, not in browsers.  as discussed in here https://github.com/vadimdemedes/net-socket/issues/2

**Comment by durairajasivam** [comment]
Yes. I am using this module with a vue. what do you want to achieve?

**Comment by roussafi-omar** [comment]
i have the same probleme,what i want to save is:
we make the git
cd to qrreader dir
npm i
npm run serve
open brower at localhost:8080
then we find error in js browser console :
[Vue warn]: Error in mounted hook: "TypeError: net__WEBPACK_IMPORTED_MODULE_2___default.a.Socket is not a constructor"
that's all

**Comment by durairajasivam** [comment]
The code meant to be used with electron with VueJs. It will not work on the browser itself.
